version: "3"
services:
  # nest:
  #   container_name: nest
  #   build: .
  #   ports:
  #     - "9001:9001"
  #   volumes:
  #     - .:/app
  #   links:
  #     - mongo

  elasticsearch:
    container_name: elasticsearch-products
    image: elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "80:80"
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nest
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
    driver: local
  elasticsearch-volume:
    driver: local

networks:
  default:
    driver: bridge
